pickme/src/main/java/project/pickme/bid/domain/Bid.java
pickme/src/main/java/project/pickme/charge/domain/Charge.java
pickme/src/main/java/project/pickme/customs/domain/Customs.java
pickme/src/main/java/project/pickme/delivery/constant/DeliveryType.java
pickme/src/main/java/project/pickme/delivery/doamin/Delivery.java
pickme/src/main/java/project/pickme/image/domain/Image.java
pickme/src/main/java/project/pickme/item/constant/Category.java
pickme/src/main/java/project/pickme/item/constant/Status.java
pickme/src/main/java/project/pickme/item/domain/Category.java
pickme/src/main/java/project/pickme/item/domain/Item.java
pickme/src/main/java/project/pickme/item/domain/ItemLaw.java
pickme/src/main/java/project/pickme/item/domain/Law.java
pickme/src/main/java/project/pickme/like/domain/Like.java
pickme/src/main/java/project/pickme/notice/domain/Notice.java
pickme/src/main/java/project/pickme/payment/domain/Payment.java
pickme/src/main/java/project/pickme/unit/domain/Unit.java
pickme/src/main/java/project/pickme/user/constant/Type.java
pickme/src/main/java/project/pickme/user/domain/User.java
pickme/src/main/resources/static/index.html
pickme/src/main/resources/templates/index.html

closes #1
변경 내용
- 카테고리, 배송현황타입 추가
- 유저, 관세청(롤 추가, 아이디 제거), 나머지 생성시간 추가
- 배송현황타입은 구현 하시는 분이 피그마 보고 추가해주세요~

[FEAT]: 초기 도메인 코드 구현

---

pickme/.gitignore
pickme/src/main/resources/application.properties

[DOCS]: 환경설정 추가, yml파일 gitignore 설정

---

pickme/build.gradle
pickme/src/main/java/project/pickme/charge/config/IamportConfig.java
pickme/src/main/java/project/pickme/charge/controller/ChargeController.java
pickme/src/main/java/project/pickme/charge/controller/ChargeRestController.java
pickme/src/main/java/project/pickme/charge/dto/ChargeDto.java
pickme/src/main/java/project/pickme/charge/mapper/ChargeMapper.java
pickme/src/main/java/project/pickme/charge/service/ChargeService.java
pickme/src/main/resources/mapper/ChargeMapper.xml
pickme/src/main/resources/static/charge/style.css
pickme/src/main/resources/templates/charge/charge.html

- closes #18 
유저 관련된 부분은 나중에 수정하겠습니다~

[FEAT]: 포인트 충전 기능 구현

---

pickme/src/main/java/project/pickme/charge/controller/ChargeController.java
pickme/src/main/java/project/pickme/charge/controller/ChargeRestController.java
pickme/src/main/java/project/pickme/charge/dto/ChargeRequest.java
pickme/src/main/java/project/pickme/charge/service/ChargeService.java
pickme/src/main/java/project/pickme/user/dto/UserDto.java
pickme/src/main/java/project/pickme/user/repository/UserMapper.java
pickme/src/main/resources/mapper/UserMapper.xml
pickme/src/main/resources/templates/charge/charge.html

- closes #22 
@Yang-soeun 유저 패키지에 코드 겹치는거 있으면 말씀해주세요~😉

[FEAT]: 포인트 충전 기능과 유저 기능 연결

---

pickme/src/main/java/project/pickme/charge/service/ChargeService.java

메서드 이름이 일괄적으로 수정되지 않아서 실행이 안되는 문제를 fix했습니다

[HOTFIX]: 컴파일 에러 수정

---

pickme/src/main/java/project/pickme/bid/dto/AddBidDto.java
pickme/src/main/java/project/pickme/bid/dto/OneBidItemDto.java
pickme/src/main/java/project/pickme/bid/repository/BidMapper.java
pickme/src/main/java/project/pickme/bid/service/BidService.java
pickme/src/main/java/project/pickme/bid/webSocket/WebSocketHandler.java
pickme/src/main/java/project/pickme/common/auth/CustomAuthenticationSuccessHandler.java
pickme/src/main/java/project/pickme/user/dto/SignUpDto.java
pickme/src/main/java/project/pickme/user/service/CustomsService.java
pickme/src/main/resources/mapper/BidMapper.xml
pickme/src/main/resources/static/css/bid/bidPage.css
pickme/src/main/resources/static/js/bid/bid.js
pickme/src/main/resources/static/js/bid/chart.js
pickme/src/main/resources/templates/bid/bidPage.html
pickme/src/test/java/project/pickme/bid/repository/BidMapperTest.java

- closes #28 
그래프 구현 참고 문헌
https://toyou101.tistory.com/24
https://www.chartjs.org/docs/latest/charts/line.html

[FEAT]: 실시간 공매 입찰 그래프 구현

---

pickme/src/main/java/project/pickme/item/FindItemService.java
pickme/src/main/java/project/pickme/item/controller/FindItemController.java
pickme/src/main/java/project/pickme/item/dto/FindItemDto.java
pickme/src/main/java/project/pickme/item/repository/FindItemMapper.java
pickme/src/main/java/project/pickme/like/controller/LikeRestController.java
pickme/src/main/java/project/pickme/like/dto/LikeDto.java
pickme/src/main/java/project/pickme/like/repository/LikeMapper.java
pickme/src/main/java/project/pickme/like/service/LikeService.java
pickme/src/main/resources/mapper/FindItemMapper.xml
pickme/src/main/resources/mapper/LikeMapper.xml
pickme/src/main/resources/static/item/css/style.css
pickme/src/main/resources/static/item/js/like.js
pickme/src/main/resources/templates/item/item.html

- closes #48 
main에서 pull 받으니까 코드가 많이 꼬여서 다시 pr 올립니다!ㅠ
아이템 리스트 화면에서 좋아요 버튼 기능은 따로 PR 올리겠습니다~!

[FEAT]: 단일 아이템 내꺼야 기능 구현

---

pickme/src/main/java/project/pickme/bid/controller/BidController.java
pickme/src/main/java/project/pickme/bid/dto/SuccessfulBidDto.java
pickme/src/main/java/project/pickme/bid/repository/BidMapper.java
pickme/src/main/java/project/pickme/bid/service/BidService.java
pickme/src/main/resources/mapper/BidMapper.xml
pickme/src/main/resources/static/css/bid/success.css
pickme/src/main/resources/templates/bid/successfulBidList.html

[FEAT]: 내 낙찰 목록 조회(배송 현황 조회)

---

pickme/src/main/java/project/pickme/item/controller/ItemController.java
pickme/src/main/java/project/pickme/item/dto/ItemFormDto.java
pickme/src/main/java/project/pickme/item/service/ItemService.java
pickme/src/main/resources/static/css/item/item.css
pickme/src/main/resources/static/js/item/item.js
pickme/src/main/resources/templates/item/createItem.html

[FEAT]: itemservice에서 s3부분 삭제

---

pickme/src/main/java/project/pickme/item/controller/ItemController.java
pickme/src/main/java/project/pickme/item/exception/ItemErrorCode.java
pickme/src/main/java/project/pickme/s3/service/S3Service.java
pickme/src/main/resources/application-s3.yml
pickme/src/main/resources/application.yml
pickme/src/main/resources/mapper/CustomsMapper.xml
pickme/src/main/resources/templates/item/createItem.html

[REFACTOR]: 에러코드부분 수정

---

pickme/src/main/resources/static/css/charge/charge.css
pickme/src/main/resources/static/css/user/myPage.css
pickme/src/main/resources/static/js/charge/charge.js
pickme/src/main/resources/templates/charge/charge.html

- closes #78 
푸터가 움직여요🥲
마이페이지 css 사이드바? width가 좀 넓은 것 같아서 30%로 수정했는데 괜찮을까요?

[STYLE]: 포인트 충전 화면 css 구현

---

pickme/src/main/java/project/pickme/user/controller/MainpageController.java
pickme/src/main/resources/mapper/FindItemMapper.xml
pickme/src/main/resources/static/css/userMain.css
pickme/src/main/resources/templates/index.html

[STYLE]: 유저 메인 페이지 디자인 개선

---

pickme/src/main/resources/static/css/common/userMainHeader.css
pickme/src/main/resources/templates/userMainHeader.html

[FEAT]: 메인페이지 전용 헤더 구현

---

pickme/src/main/resources/static/css/item/detail.css
pickme/src/main/resources/static/js/item/countdown.js
pickme/src/main/resources/templates/item/item.html

#93 
전체적인 사이즈 줄였고 px대신 다른것들,, 써봤는데 아직 완전하진 않습니당

[FIX]: 화면 연결 문제 수정 및 화면 요소 크기 수정

---

pickme/src/main/resources/templates/delivery/delivery.html

[STYLE]: 배송 관리 페이지 헤더 적용

---

pickme/src/main/java/project/pickme/PickmeApplication.java
pickme/src/main/java/project/pickme/item/repository/ItemMapper.java
pickme/src/main/java/project/pickme/item/service/ItemSchedulingService.java
pickme/src/main/resources/mapper/ItemMapper.xml

[FEAT]: 아이템 상태 변경 기능 구현

---

pickme/src/main/java/project/pickme/item/controller/FindItemController.java
pickme/src/main/java/project/pickme/item/repository/FindItemMapper.java
pickme/src/main/java/project/pickme/item/service/FindItemService.java
pickme/src/main/resources/mapper/FindItemMapper.xml
pickme/src/main/resources/static/css/item/list.css
pickme/src/main/resources/templates/item/list.html

- closes #123 
카테고리 목록에 전체보기 같은것도 추가하는게 좋을까여? 카테고리 하나 버튼 누르면 전체조회로 돌아올 방법이 없어서유

[FEAT]: 카테고리 필터링 기능 추가

---

pickme/src/main/java/project/pickme/item/controller/ItemController.java
pickme/src/main/java/project/pickme/item/dto/ItemFormDto.java
pickme/src/main/java/project/pickme/user/controller/MainController.java
pickme/src/main/java/project/pickme/user/controller/UserController.java
pickme/src/main/resources/static/css/bid/bidPage.css
pickme/src/main/resources/static/css/customs/customsSidebar.css
pickme/src/main/resources/static/css/item/item.css
pickme/src/main/resources/static/css/item/list.css
pickme/src/main/resources/static/js/item/item.js
pickme/src/main/resources/templates/bid/bidPage.html
pickme/src/main/resources/templates/customs/customsSidebar.html
pickme/src/main/resources/templates/item/createItem.html
pickme/src/main/resources/templates/item/customsItems.html
pickme/src/main/resources/templates/layouts/layout.html

[FEAT]: 공매품 작성 페이지 화면 구현

---

pickme/src/main/resources/templates/delivery/delivery.html

[FEAT]: 배송관리 페이지 사이드바 적용

---

pickme/src/main/java/project/pickme/item/repository/FindItemMapper.java
pickme/src/main/resources/mapper/FindItemMapper.xml
pickme/src/main/resources/static/css/item/list.css
pickme/src/main/resources/templates/item/list.html

[REFACTOR]: 없어진 코드 복구

---

pickme/src/main/resources/static/css/item/detail.css
pickme/src/main/resources/templates/item/item.html

- closes #150 
좀 작게 한다고 했는데 작나요?

[STYLE]: 아이템 상세조회 css 수정

---

pickme/src/main/resources/static/css/common/footer.css
pickme/src/main/resources/static/css/common/header.css
pickme/src/main/resources/static/css/item/list.css
pickme/src/main/resources/static/css/user/infoEdit.css
pickme/src/main/resources/templates/fragments/footer.html
pickme/src/main/resources/templates/fragments/header.html
pickme/src/main/resources/templates/item/list.html

[STYLE]: User/Customs 헤더 디자인 통일

---

pickme/src/test/java/project/pickme/user/repository/CustomsMapperTest.java

[FIX]: 테스트 오류 수정

---

pickme/src/main/resources/application.yml

[CHORE]: yml 파일 수정

---

pickme/src/main/resources/static/css/common/header.css
pickme/src/main/resources/static/css/customs/customsHeader.css
pickme/src/main/resources/templates/customs/customsHeader.html
pickme/src/main/resources/templates/fragments/header.html

- closes #164 
- 요청사항 : 현재 로그아웃 버튼 클릭 시 로그아웃 후 /user/main으로 가고싶은데 단순 href로는 로그아웃 되지 않은 상태로 이동됨.  확인해보니 시큐리티쪽에서 처리가 필요하다고 하는데 조언 주시면 감사하겠습니다~
- merge 후 헤더 애니메이션 잘 작동되는지 확인 부탁드려요~

[STYLE]: 메인 헤더 및 각종 디자인 개선

---

pickme/src/main/java/project/pickme/common/auth/CustomsDetailsImpl.java
pickme/src/main/java/project/pickme/common/auth/UserDetailsImpl.java
pickme/src/main/java/project/pickme/common/config/WebSecurityConfig.java
pickme/src/main/resources/application.yml
pickme/src/main/resources/static/js/bid/bid.js
pickme/src/main/resources/templates/customs/customsHeader.html
pickme/src/main/resources/templates/fragments/header.html
pickme/src/test/java/project/pickme/bid/repository/BidMapperTest.java
pickme/src/test/java/project/pickme/item/repository/FindItemMapperTest.java
pickme/src/test/java/project/pickme/payment/repository/PaymentMapperTest.java
pickme/src/test/java/project/pickme/user/repository/CustomsMapperTest.java
pickme/src/test/java/project/pickme/user/repository/UserMapperTest.java

- closes #166 
- UserDetails 구현체에 equals, hashCode 재정의 해서 동일한 객체로 인식하도록 해서 해결

[FIX]: 스프링 시큐리티 동시 로그인 차단 안되는 문제 해결

---

pickme/src/main/java/project/pickme/notice/repository/NoticeMapper.java
pickme/src/main/java/project/pickme/notice/service/CampaignService.java
pickme/src/main/java/project/pickme/user/controller/MainController.java
pickme/src/main/resources/mapper/NoticeMapper.xml
pickme/src/main/resources/static/css/userMain.css
pickme/src/main/resources/static/js/userMain.js
pickme/src/main/resources/templates/index.html

- closes #130 
- 캠페인 업로드 시간 기준 최신 4개 출력
- 이미지가 깨지지 않게하는 기준에서 좌우를 맞추면 이미지가 위아래로 잘림
- 잘리는 이미지 예시(아래의 장소 등이 출력되지 않음)

[FEAT]: 메인 페이지 캠페인 페이지네이션

---

pickme/src/main/java/project/pickme/bid/controller/BidController.java
pickme/src/main/java/project/pickme/bid/controller/BidRestController.java
pickme/src/main/java/project/pickme/bid/repository/BidMapper.java
pickme/src/main/java/project/pickme/bid/service/BidService.java
pickme/src/main/java/project/pickme/payment/repository/PaymentMapper.java
pickme/src/main/resources/mapper/BidMapper.xml
pickme/src/main/resources/mapper/PaymentMapper.xml
pickme/src/main/resources/static/js/bid/successfulBidList.js
pickme/src/main/resources/templates/bid/mySuccessfulBidList.html
pickme/src/main/resources/templates/fragments/myPageSidebar.html

[FEAT]: 내 결제 목록 페이지네이션 적용

---

pickme/src/main/java/project/pickme/item/dto/FindItemDto.java
pickme/src/main/resources/mapper/FindItemMapper.xml
pickme/src/main/resources/static/js/item/wishList.js
pickme/src/main/resources/templates/item/item.html
pickme/src/main/resources/templates/item/wishList.html

[FIX]: 좋아요 오류 수정

---

pickme/src/main/java/project/pickme/charge/controller/ChargeRestController.java
pickme/src/main/java/project/pickme/item/controller/FindUserItemController.java
pickme/src/main/java/project/pickme/item/controller/FindUserItemRestController.java
pickme/src/main/java/project/pickme/item/dto/FindItemDto.java
pickme/src/main/java/project/pickme/item/dto/ItemRequest.java
pickme/src/main/java/project/pickme/item/repository/FindItemMapper.java
pickme/src/main/java/project/pickme/item/service/FindItemService.java
pickme/src/main/java/project/pickme/like/controller/LikeRestController.java
pickme/src/main/resources/mapper/FindItemMapper.xml
pickme/src/main/resources/static/css/item/detail.css
pickme/src/main/resources/static/css/item/wishList.css
pickme/src/main/resources/static/js/item/BidInfiniteScroll.js
pickme/src/main/resources/static/js/item/bidList.js
pickme/src/main/resources/static/js/item/infiniteScroll.js
pickme/src/main/resources/static/js/item/infiniteScroll2.js
pickme/src/main/resources/templates/item/bidList.html
pickme/src/main/resources/templates/item/item.html
pickme/src/main/resources/templates/item/list.html
pickme/src/main/resources/templates/item/wishList.html

[FEAT]: 입찰 목록 페이지네이션 구현 & 비동기 처리

---

pickme/src/main/resources/static/css/item/detail.css
pickme/src/main/resources/templates/item/item.html

- closes #197 
법규 모달창 가로 길이가 너무 작아서 늘렸습니다!

[STYLE]: 법규 모달창 사이즈 조절

---

pickme/src/main/java/project/pickme/item/controller/FindUserItemRestController.java
pickme/src/main/resources/application.yml
pickme/src/main/resources/mapper/ItemMapper.xml
pickme/src/main/resources/static/css/item/detail.css
pickme/src/main/resources/templates/item/item.html

- closes #209 
배포한 뒤에 관심상품 목록이 조회가 안돼서 db 로깅 설정 추가했습니다
자잘한 수정사항이 많아서 (이슈만들기가 너무 귀찮아서 ㅠㅠ) 이 pr에다가 올립니다,, 양해부탁드립니다

[CHORE]: mybatis logging 설정

---

pickme/src/main/java/project/pickme/bid/controller/BidController.java
pickme/src/main/java/project/pickme/image/repository/ImageMapper.java
pickme/src/main/resources/mapper/ImageMapper.xml

[FEAT]: image bulk insert 오류 수정

---

pickme/src/main/java/project/pickme/bid/controller/BidController.java
pickme/src/main/java/project/pickme/bid/dto/reqeust/SelectedBidDto.java
pickme/src/main/java/project/pickme/bid/repository/BidMapper.java
pickme/src/main/java/project/pickme/bid/service/BidSchedulingService.java
pickme/src/main/java/project/pickme/delivery/repository/DeliveryMapper.java
pickme/src/main/java/project/pickme/image/repository/ImageMapper.java
pickme/src/main/java/project/pickme/user/service/CustomsService.java
pickme/src/main/resources/mapper/BidMapper.xml
pickme/src/main/resources/mapper/DeliveryMapper.xml
pickme/src/main/resources/mapper/FindItemMapper.xml
pickme/src/main/resources/mapper/ImageMapper.xml
pickme/src/main/resources/mapper/ItemLawMapper.xml
pickme/src/main/resources/mapper/ItemMapper.xml
pickme/src/main/resources/mapper/NoticeMapper.xml
pickme/src/main/resources/mapper/StatisticsMapper.xml
pickme/src/main/resources/mapper/UserMapper.xml
pickme/src/main/resources/static/css/bid/success.css
pickme/src/main/resources/static/js/bid/successfulBidList.js
pickme/src/main/resources/static/js/bid/unpaidBid.js
pickme/src/main/resources/templates/bid/mySuccessfulBidList.html
pickme/src/main/resources/templates/bid/unpaidBidList.html
pickme/src/main/resources/templates/index.html
pickme/src/test/java/project/pickme/bid/controller/BidRestControllerTest.java
pickme/src/test/java/project/pickme/item/repository/FindItemMapperTest.java
pickme/src/test/java/project/pickme/user/repository/UserMapperTest.java

[FEAT]: 낙찰 관련 오류 수정

---

pickme/src/main/resources/mapper/CustomsMapper.xml

[REFACTOR]: 수입 조회 쿼리 결제 내역 조건 추가

---

pickme/src/main/resources/static/css/bid/success.css
pickme/src/main/resources/static/css/delivery/status.css
pickme/src/main/resources/templates/bid/mySuccessfulBidList.html
pickme/src/main/resources/templates/delivery/userStatus.html

[REFACTOR]: 테이블 너비 변경

---

pickme/src/main/resources/static/css/userMain.css

[STYLE]: 메인 화면 아이템 hover 효과 추가

---

pickme/src/main/resources/static/js/customs/income.js
pickme/src/main/resources/static/js/user/myPage.js

[REFACTOR]: 수입이 없는 경우 기본 포인트 0으로 설정

---

pickme/src/test/java/project/pickme/user/repository/CustomsMapperTest.java

[FIX]: 수익 확인 테스트 코드 오류 수정

---

pickme/src/main/java/project/pickme/bid/controller/BidRestController.java
pickme/src/main/java/project/pickme/bid/service/BidSchedulingService.java
pickme/src/main/java/project/pickme/bid/service/BidService.java
pickme/src/main/resources/static/js/bid/unpaidBid.js

[FIX]: 결제 후 다시 화면 load 하도록 수정

---

pickme/src/main/resources/static/css/item/item.css

[REFACTOR]: 세관쪽 content 위치 조정

---

pickme/src/main/java/project/pickme/bid/service/BidSchedulingService.java
pickme/src/main/java/project/pickme/item/service/ItemSchedulingService.java
pickme/src/main/resources/mapper/StatisticsMapper.xml
pickme/src/main/resources/templates/customs/customsSidebar.html
pickme/src/main/resources/templates/index.html

[FEAT]: 통계페이지 구현 및 디자인 개선

---

pickme/src/main/resources/static/css/statistics/dashboard.css

[STYLE]: 대시보드 배경 페이지 변경

---

pickme/src/main/java/project/pickme/bid/service/MailService.java

[FIX]: "/user/bidMail" url / 제거

---

pickme/src/main/java/project/pickme/bid/controller/BidRestController.java
pickme/src/main/java/project/pickme/delivery/constant/DeliveryType.java
pickme/src/main/java/project/pickme/delivery/controller/DeliveryRestController.java
pickme/src/main/java/project/pickme/delivery/doamin/Delivery.java
pickme/src/main/java/project/pickme/item/controller/ItemRestController.java
pickme/src/main/resources/static/css/delivery/userStatus.css

[DOCS]: javaDoc추가
